#!/bin/bash
# Debug接口自动化测试脚本 - Babysitter使用

EASYSSH="./src-tauri/target/debug/easyssh.exe"
LOG_FILE="debug-test-report.md"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

# 颜色
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  EasySSH Debug接口自动化测试${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# ========== Rust模块测试 ==========
echo -e "${YELLOW}[1/4] 运行Rust模块测试...${NC}"

TEST_OUTPUT=$(cargo test --manifest-path src-tauri/Cargo.toml 2>&1)
TEST_EXIT=$?

TOTAL_TESTS=$(echo "$TEST_OUTPUT" | grep -o "[0-9]* passed" | head -1 | cut -d' ' -f1)
FAILED_TESTS=$(echo "$TEST_OUTPUT" | grep -o "[0-9]* failed" | head -1 | cut -d' ' -f1)

if [ "$TEST_EXIT" -eq 0 ]; then
    echo -e "${GREEN}✅ Rust测试通过 ($TOTAL_TESTS passed)${NC}"
else
    echo -e "${RED}❌ Rust测试失败${NC}"
    echo "$TEST_OUTPUT" | tail -20
fi

# ========== TypeScript检查 ==========
echo ""
echo -e "${YELLOW}[2/4] 运行TypeScript检查...${NC}"

TS_OUTPUT=$(npx tsc --noEmit 2>&1)
TS_EXIT=$?

if [ "$TS_EXIT" -eq 0 ]; then
    echo -e "${GREEN}✅ TypeScript检查通过${NC}"
else
    echo -e "${RED}❌ TypeScript检查失败${NC}"
    echo "$TS_OUTPUT"
fi

# ========== Cargo编译检查 ==========
echo ""
echo -e "${YELLOW}[3/4] 运行Cargo编译检查...${NC}"

CHECK_OUTPUT=$(cargo check --manifest-path src-tauri/Cargo.toml 2>&1)
CHECK_EXIT=$?

if [ "$CHECK_EXIT" -eq 0 ]; then
    echo -e "${GREEN}✅ Cargo编译检查通过${NC}"
else
    echo -e "${RED}❌ Cargo编译检查失败${NC}"
    echo "$CHECK_OUTPUT" | tail -10
fi

# ========== 前端构建 ==========
echo ""
echo -e "${YELLOW}[4/4] 运行前端构建...${NC}"

BUILD_OUTPUT=$(npm run build 2>&1)
BUILD_EXIT=$?

if [ "$BUILD_EXIT" -eq 0 ]; then
    JS_SIZE=$(echo "$BUILD_OUTPUT" | grep -o "[0-9]*\.[0-9]* KB" | tail -1)
    CSS_SIZE=$(echo "$BUILD_OUTPUT" | grep -o "[0-9]*\.[0-9]* KB" | head -1)
    echo -e "${GREEN}✅ 前端构建成功${NC}"
    echo "   Bundle: index.js $JS_SIZE, index.css $CSS_SIZE"
else
    echo -e "${RED}❌ 前端构建失败${NC}"
fi

# ========== 生成报告 ==========
echo ""
echo -e "${YELLOW}生成测试报告...${NC}"

cat > "$LOG_FILE" << EOF
# EasySSH Debug接口测试报告

## 测试信息
- 测试时间: $TIMESTAMP
- 测试版本: v0.2.0

## 测试结果汇总

| 测试项 | 状态 | 详情 |
|--------|------|------|
| Rust单元测试 | $([ "$TEST_EXIT" -eq 0 ] && echo "✅ PASS" || echo "❌ FAIL") | $TOTAL_TESTS passed, ${FAILED_TESTS:-0} failed |
| TypeScript检查 | $([ "$TS_EXIT" -eq 0 ] && echo "✅ PASS" || echo "❌ FAIL") | - |
| Cargo编译检查 | $([ "$CHECK_EXIT" -eq 0 ] && echo "✅ PASS" || echo "❌ FAIL") | - |
| 前端构建 | $([ "$BUILD_EXIT" -eq 0 ] && echo "✅ PASS" || echo "❌ FAIL") | $JS_SIZE |

## Debug接口列表

### AI编程接口
| 接口 | 功能 |
|------|------|
| ai_health_check | 健康检查 |
| ai_read_code | 读取文件 |
| ai_list_files | 列出目录 |
| ai_search_code | 搜索代码 |
| ai_check_rust | Rust检查 |
| ai_run_tests | 运行测试 |
| ai_build | 构建项目 |

### Git操作接口
| 接口 | 功能 |
|------|------|
| git_status | Git状态 |
| git_diff | 代码差异 |
| git_log | 提交历史 |
| git_branch | 分支列表 |

### 代码修改接口
| 接口 | 功能 |
|------|------|
| write_file | 写入文件 |
| edit_file | 编辑文件 |

### 上下文管理接口
| 接口 | 功能 |
|------|------|
| set_context | 设置上下文 |
| get_context | 获取上下文 |
| clear_context | 清空上下文 |

### 模块测试接口
| 接口 | 功能 |
|------|------|
| debug_quick_check | 快速检查 |
| debug_test_all | 全量测试 |
| debug_test_db | 数据库测试 |
| debug_test_crypto | 加密测试 |
| debug_test_ssh | SSH测试 |
| debug_test_pro | Pro模块测试 |
| debug_test_terminal | Terminal测试 |

## Rust测试详情

\`\`\`
$TEST_OUTPUT
\`\`\`

---
* Generated by EasySSH Babysitter v0.2.0 *
EOF

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  测试完成！报告已保存到: $LOG_FILE${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# 最终检查结果
if [ "$TEST_EXIT" -eq 0 ] && [ "$TS_EXIT" -eq 0 ] && [ "$CHECK_EXIT" -eq 0 ] && [ "$BUILD_EXIT" -eq 0 ]; then
    echo -e "${GREEN}🎉 所有测试通过！${NC}"
    exit 0
else
    echo -e "${RED}⚠️  部分测试失败，请检查报告${NC}"
    exit 1
fi
