name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo run -p easyssh-test -- fmt
      - run: cargo run -p easyssh-test -- clippy
      - run: cargo run -p easyssh-test -- test
      - run: cargo run -p easyssh-test -- build --profile release
